### PR TITLE
Refactor database, add budget creation and retreival, update user interface, add predefined budget to user

### LINKED ISSUE #16: Implement budget retrieval

### PR DESCRIPTION
**Pull request by icextreme**

### CODE REVIEW

**Comment by truongnguyenlinh** [comment]
So in order to refactor the db:
- Account for the "Add Budget" activity string values
- Add these values which the user inputs from "Add Budget" activity to the DB
- Update the Budget Spinner to read from the DB instead of the hardcoded string values 
- The "+ New Budget" value should be at the top, so that when a user adds a new budget, it goes to the bottom of the spinner.

**Comment by icextreme** [comment]
>     * Update the Budget Spinner to read from the DB instead of the hardcoded string values

There will be an empty list of budgets, or rather a null value if that is the case. Should there be a predefined starter budget?

**Comment by truongnguyenlinh** [comment]
Maybe a predefined budget would be best. Each user will have a default "expenses" budget.

**Comment by icextreme** [comment]
> Maybe a predefined budget would be best. Each user will have a default "expenses" budget.

On user creation
image

**Comment by icextreme** [comment]
Changed base to `master` as `data` will not be worked on anymore.

**Pull request merged**
